version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./:/app
    working_dir: /app

  webserver:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: proveedores
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony-data:/var/lib/mysql

volumes:
  symfony-data: